# Generated by Django 3.2.15 on 2022-09-21 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=100)),
                ('edad', models.EmailField(max_length=254)),
                ('peso', models.CharField(max_length=15)),
                ('frecuencia_cardiaca', models.CharField(max_length=15)),
                ('spo2', models.CharField(max_length=15)),
                ('nivel_estres', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
